name: docs

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Use node v16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: load dependences
        run: |
          npm run bootstrap

      - name: generate static file
        run: |
          npm run build:types
          npm run build
          rm -rf ./deploy
          mkdir -p deploy/examples
          cp -rf ./docs/.vuepress/index.html ./deploy
          cp -rf ./examples/build/* ./deploy/examples

      - name: generate mvp
        run: |
          cd ./site/mvp
          npm install
          npm run build
          cd ../../
          mkdir -p deploy/mvp
          cp -rf ./site/mvp/dist/* ./deploy/mvp

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: logic-flow.org
          
